In [28]:
import pandas as pd
import math

In [29]:
def is_prime(n):
    for i in range(2,n):
        if (n%i) == 0:
            return False
    return True

df = pd.Series([i for i in range(10)])

print(df.apply(lambda x: x if is_prime(x) else 0))

0    0
1    1
2    2
3    3
4    0
5    5
6    0
7    7
8    0
9    0
dtype: int64

In [30]:
a = [i for i in range(10)]
a[4] = None
df = pd.Series(a)

print(df.apply(lambda x: 0 if pd.isna(x) else x))

0    0.0
1    1.0
2    2.0
3    3.0
4    0.0
5    5.0
6    6.0
7    7.0
8    8.0
9    9.0
dtype: float64

In [31]:
a = [i for i in range(10)]
a[3] = None
a[5] = None


df = pd.Series(a)
preve = 0
for i, x in enumerate(df):
    if pd.isna(x):
        df[i] = preve
    else:
        preve = x
df

0    0.0
1    1.0
2    2.0
3    2.0
4    4.0
5    4.0
6    6.0
7    7.0
8    8.0
9    9.0
dtype: float64

In [32]:
a = [i for i in range(10)]
a[3] = None
a[5] = None
df = pd.Series(a)
mean = df.mean()
for i, x in enumerate(df):
    if pd.isna(x):
        df[i] = mean
 
df

0    0.000
1    1.000
2    2.000
3    4.625
4    4.000
5    4.625
6    6.000
7    7.000
8    8.000
9    9.000
dtype: float64

In [33]:
a = [i for i in range(10)]
a[3] = None
a[5] = None
df = pd.Series(a)


df = df[df.isna() != True]
print(df)

0    0.0
1    1.0
2    2.0
4    4.0
6    6.0
7    7.0
8    8.0
9    9.0
dtype: float64

In [34]:
a = [i for i in range(10)]
a[3] = None
a[5] = None
df = pd.Series(a)

def check_for_mising(df):
    if True in df.isna().tolist():
        return False
    return True


check_for_mising(df)

False

In [35]:
a = ["adf", "adsgfao", "sdgfsf", "dsf", "dagarg"]
df = pd.Series(a)

print(df.apply(lambda x: len(x)))

0    3
1    7
2    6
3    3
4    6
dtype: int64

In [36]:
a = [i for i in range(10)]

df = pd.Series(a)

print(df.apply(lambda x: "even" if x%2==0 else "odd"))

0    even
1     odd
2    even
3     odd
4    even
5     odd
6    even
7     odd
8    even
9     odd
dtype: object

In [37]:
a = ["adf", "adsgfao", "sdgfsf", "dsf", "dagarg"]
df = pd.Series(a)

df = df.apply(lambda x: x[::-1])
df

0        fda
1    oafgsda
2     fsfgds
3        fsd
4     gragad
dtype: object

In [38]:
data = { 'Name': ['Anna', 'Ben', 'Charlie', 'Dana', 'Eli', 'Franz', 'Grace'], 'Alter': [23, 31, 35,
29, 42, 26, 28], 'Stadt': ['Berlin', 'Hamburg', 'Frankfurt', 'Köln', 'Stuttgart', 'München',
'Dresden'] }
df = pd.DataFrame(data)

In [39]:
df["Name"].iloc[3]

'Dana'

In [40]:
df.set_index("Name", inplace=True)

In [41]:

df.loc["Eli"]

Alter           42
Stadt    Stuttgart
Name: Eli, dtype: object

In [42]:
df["Alter"].loc["Dana"]

29

In [43]:
df = pd.DataFrame(data)

df["Alter"].iloc[:3]

0    23
1    31
2    35
Name: Alter, dtype: int64

In [44]:
df["Stadt"].iloc[:3:-1]

6      Dresden
5      München
4    Stuttgart
Name: Stadt, dtype: object

In [45]:
df.set_index("Name", inplace=True)
df["Alter"].loc["Ben"] = 32

df = pd.DataFrame(data)

C:\Users\morit\AppData\Local\Temp\ipykernel_3616\2998723862.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Alter"].loc["Ben"] = 32

In [46]:
df = pd.DataFrame(data)
df.set_index("Stadt", inplace=True)
print(df.loc[df.index.str.startswith('B', na=False)] )

df = pd.DataFrame(data)

        Name  Alter
Stadt
Berlin  Anna     23

In [47]:
df = pd.DataFrame(data)
df.loc[len(df.index)] = ["Hans", 40, "Leipzig"]
df

      Name  Alter      Stadt
0     Anna     23     Berlin
1      Ben     31    Hamburg
2  Charlie     35  Frankfurt
3     Dana     29       Köln
4      Eli     42  Stuttgart
5    Franz     26    München
6    Grace     28    Dresden
7     Hans     40    Leipzig

In [48]:
df = pd.DataFrame(data)

df.set_index("Stadt", inplace=True)
print(df.loc[df.index.str.len() == 6] )
df = pd.DataFrame(data)

        Name  Alter
Stadt
Berlin  Anna     23

In [52]:
print(df)
for i, x in df.iterrows():
    if x.Alter > 40:
        df.drop(i)
df.reset_index()
print(df)

      Name  Alter      Stadt
0     Anna     23     Berlin
1      Ben     31    Hamburg
2  Charlie     35  Frankfurt
3     Dana     29       Köln
4      Eli     42  Stuttgart
5    Franz     26    München
6    Grace     28    Dresden
      Name  Alter      Stadt
0     Anna     23     Berlin
1      Ben     31    Hamburg
2  Charlie     35  Frankfurt
3     Dana     29       Köln
4      Eli     42  Stuttgart
5    Franz     26    München
6    Grace     28    Dresden

In [79]:


idk = {
    "Größe":{
        "Franz": 1.82,    
        "Charly": 1.65,
        "Tomi": 1.78    
    },
    "Gewicht":{
        "Franz": 80,                
        "Charly": 75,            
        "Tomi": 61                
    }
}

df = pd.DataFrame(idk)
df

        Größe  Gewicht
Franz    1.82       80
Charly   1.65       75
Tomi     1.78       61

In [80]:
bmis = []
for i, x in df.iterrows():
    print(i)
    bmi = x.Gewicht/(x.Größe)**2
    bmis.append(bmi)

    print("BMI: " + str(bmi))
    if bmi >= 18.5 and bmi<= 25:
        print("normalen Bereich")
    print()

Franz
BMI: 24.151672503320853
normalen Bereich

Charly
BMI: 27.548209366391188

Tomi
BMI: 19.252619618735007
normalen Bereich

In [78]:
for i, x in df.iterrows():
    if "i" in i:
        print(i)

Tomi

In [82]:
df = df.assign(bmi=bmis)
df

        Größe  Gewicht        bmi
Franz    1.82       80  24.151673
Charly   1.65       75  27.548209
Tomi     1.78       61  19.252620